# setup-cgroups
# The systemd cgroup only used when systemd start with cgroupv1
# You can set MOUNT_CGROUP_SYSTEMD=false when your container start with cgroupv2,
# or start without systemd, or you just don't want to mount systemd cgroup.
MOUNT_CGROUP_SYSTEMD=true
# auto-start-stop
AUTO_START_STOP=false   # No auto start/stop android
MAX_ATTEMPTS=4
ONLINE_WEBSITES="8.8.8.8
233.5.5.5"
SLEEP_TIME=600
# setup-network
SETUP_NETWORK=true
device_interface="wlan0 eth0"
# setup-docker
SETUP_DOCKER=true
